[package]
description = "Parity Miner interface."
name = "ethcore-miner"
homepage = "http://parity.io"
license = "GPL-3.0"
version = "1.9.0"
authors = ["Parity Technologies <admin@parity.io>"]

[dependencies]
# TODO [ToDr] Rewrite using reqwest
hyper = { git = "https://github.com/paritytech/hyper", default-features = false }

ansi_term = "0.10"
error-chain = "0.11"
ethabi = "5.1"
ethabi-contract = "5.0"
ethabi-derive = "5.0"
ethash = { path = "../ethash" }
ethcore-transaction = { path = "../ethcore/transaction" }
ethereum-types = "0.2"
futures = "0.1"
heapsize = "0.4"
keccak-hash = { path = "../util/hash" }
linked-hash-map = "0.5"
log = "0.3"
parking_lot = "0.5"
price-info = { path = "../price-info" }
rayon = "1.0"
trace-time = { path = "../util/trace-time" }
transaction-pool = { path = "../transaction-pool" }

[dev-dependencies]
ethkey = { path = "../ethkey" }
rustc-hex = "1.0"
